### ISSUE TITLE
DSJulia Registry

### ISSUE THREAD

**Issue by wardvanbelle** [Beramos/DS-Julia2925#107]
At the moment there is no way of using the Pluto pkg manager while also using the DSJulia package. There are two ways to solve this:
1. By registering DSJulia
2. By making a whole environment with DSJulia, PlutoUI and all other dependencies.

**Comment by MichielStock** [comment]
@DaanVanHauwermeiren and @Beramos If ok for you, I will register the package after verifying that it is more or less definitive.

**Comment by Beramos** [comment]
@JuliaRegistrator register()

**Comment by Beramos** [comment]
There are still some potential problems with registering this package see [this PR](https://github.com/JuliaRegistries/General/pull/43037).

We need to consider 
- [ ] Matching package name and repo name
- [ ] Filling in the compatibility of the julia versions
- [ ]  We might need to make the package name longer to avoid a name clash with IJulia and OMJulia


but might have unexpected repercussions that need to be discussed/tested first.

**Comment by MichielStock** [comment]
Hmm, might indeed be more trouble than worth. The solution suggested on slack is also not necessarily a panacea. 

![imgpsh_mobile_save](https://user-images.githubusercontent.com/6018979/129750195-abf8306c-e555-4865-9199-fba4c9bbedb7.jpg)

I solved this for a student using `Pkg.activate(".")`. Then we main package manager again.

**Comment by Beramos** [comment]
Agreed

**Comment by MichielStock** [comment]
Maybe, we might best just diable the Pluto pkg manager and install DSJulia manually? All other options seem worse.

**Comment by Beramos** [comment]
Best to be discussed on Friday, I'm not up-to-date with inner workings of
the Pluto pkg manager.

Op wo 18 aug. 2021 om 14:11 schreef Michiel Stock ***@***.***

**Comment by DaanVanHauwermeiren** [comment]
we are no longer using DSJulia, closing
