### ISSUE TITLE
Notebook 2: validator riemansum

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#112]
**Describe the bug**
Validator Riemansum seems to be a bit too strict. Need to double check this 

**To Reproduce**
Notebook 2: question 1

**Comment by Beramos** [comment]
It appears that the first subquestion is very loosy goosy but the second and third still use equality
https://github.com/Beramos/DS-Julia2925/blob/8496d623f9836bec1db9a4daf882f484ad87a0a9/notebooks/day1/02-collections.jl#L717

**Comment by DaanVanHauwermeiren** [comment]
no more questionblocks, closing
