### ISSUE TITLE
Consistency in the Pkg treatment

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#117]
Some notebooks have a different way of loading the dependencies 
e.g. 
**day2/notebook1**

https://github.com/Beramos/DS-Julia2925/blob/8496d623f9836bec1db9a4daf882f484ad87a0a9/notebooks/day2/01-types.jl#L29

**day2/notebook2**

https://github.com/Beramos/DS-Julia2925/blob/8496d623f9836bec1db9a4daf882f484ad87a0a9/notebooks/day2/02-composite_types.jl#L29

**day2/metaprogramming**
https://github.com/Beramos/DS-Julia2925/blob/8496d623f9836bec1db9a4daf882f484ad87a0a9/notebooks/day2/03-metaprogramming.jl#L9

Let us follow @MichielStock's idea and provide a separate packaged that can be put in the package repository which contains:
* The questionblock functionality with verification
* Dependencies of the notebooks

**Comment by DaanVanHauwermeiren** [comment]
no longer relevant
