### ISSUE TITLE
improvement flatland

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [Beramos/DS-Julia2925#127]
improve the large exercise for day 2

Change the story to: 

We have elves
They elves haves N randomly generated fields of with a shape of a rectangle, circle, or triangle. (Once you choose a field shape, all fields have the same shape)
Given these fields, the elves have some questions:
1. What is the total surface area of all fields?
2. How many fields overlap?
3. What is the total overlap surface area?
4. sort the fields from small to larger surface areas (hint: do some multiple dispatch magic on e.g. `<`)
Start from the primary field shape of a rectangle, this is the simplest solution. Afterwards, try to find the solution for circles or triangles.

Optional questions:
1. plot the fields using `plotRecipes`
2. Take out r fields so that none are overlapping, what is the maximum total surface area of all fields?
3. combine the lists of rectangular, circular and triangular fields, repeat all previous questions.

Notes:
overlap of N circles:
- within the combinded bounding boxes of all circles
- sample within the rectangle: how many fall within at least 1 circle?
point within triangle:
- point must lie on the same side of the line as defined by two points

Todo
- [x] generate random fields: fix seed and generate some random numbers
- [x] compute surface area
- [x] comparison of shapes
- [x] define overlap
- [x] compute overlap surface area
- [x] DO NOT give solutions for the optional questions

Tasks:
@MichielStock first draft
@Beramos clean up
@DaanVanHauwermeiren solve final notebook

**Comment by MichielStock** [comment]
@Beramos I outlined the project with a solution for circles. Would you like to draft the story? I will remove the solutions and then finalize it.

**Comment by Beramos** [comment]
super, thx! I will start coming weekend

Op di 3 jan. 2023 om 15:17 schreef Michiel Stock ***@***.***>:

**Comment by DaanVanHauwermeiren** [comment]
Can I give this a go @Beramos @MichielStock ?

**Comment by MichielStock** [comment]
Zal morgen kijken
