### ISSUE TITLE
Adding a package in this repository

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#28]
I have been struggling for a while to include a package in the src/ directory. Things I tried:
* include("path/to/package.jl") -> not clean and does not work in Pluto
* Changing the whole DS repo in a package -> Can't activate the environment and then import a package that uses the same environment
* Constructing a scenario where the package is in the src directory, e.g. src/TeachingsTools.jl/src/TeachingsTools.jl -> A package needs to be a git repository but you can not put a git repo within a git repo 

Solutions that will probably work but that I don't like:
* Create a separate repository for the package and using it as a sub-module in this repo

The solution is probably something trivial but I just can't figure it out...

**Comment by MichielStock** [comment]
You can install this repo code: 
`using("Pkg"); Pkg.add("https://github.com/Beramos/DS-Julia2925")`
allows using this package.
The only thing I am not sure of, is that the "-" in the name won't give troubles.

**Comment by MichielStock** [comment]
I will do this this afternoon.

**Comment by Beramos** [comment]
Dat lukt idd maar toen ik in pluto de enviroment activate dan zegt hij can't activate an environment that uses the same uuid as a package. Dus dan moeten we al een separate environment aanmaken. I guess

**Comment by MichielStock** [comment]
You can now install the package from the master. Use `generate` in the package manager for subsequent projects. This will generate correct `project.toml`.

**Comment by Beramos** [comment]
Did you try activating the environment from pluto?

**Comment by Beramos** [comment]
#29

**Comment by MichielStock** [comment]
You can install the package from the REPL and then it runs?

**Comment by Beramos** [comment]
I'll give it another test tonight

**Comment by Beramos** [comment]
Still the same issue 
![image](https://user-images.githubusercontent.com/11618908/101353902-a46f3980-3894-11eb-8fd0-590e3ef0df7c.png)

**Comment by Beramos** [comment]
Dit werkt
![image](https://user-images.githubusercontent.com/11618908/101354046-cff22400-3894-11eb-8bc4-43c44b1ca294.png)
Maar dan zit je te wereken op een andere enviroment dan project.toml in de root van deze repo. 

Volgens mij moeten we dan met twee project.tomls werken.

- project.toml
- notebooks
|-- project.toml

Optie 2

**Comment by MichielStock** [comment]
Just install it in the REPL and only load it in the notebook?

**Comment by Beramos** [comment]
Nop: 
![image](https://user-images.githubusercontent.com/11618908/101386062-eca25200-38bc-11eb-950d-7a78dcab255e.png)
