### ISSUE TITLE
Notebook 1: proofreading + question testing

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#44]
- [x] Proofread for spelling mistakes
- [x] All questions either have working and correct validators or don't need validators
- [x] All QuestionBlocks seem to work fine
- [x] All validators use the `@safe[] ` macro

**Comment by Beramos** [comment]
since #46 notebook 1 is in a pretty nice state so it can be proof read and battle tested

**Comment by MichielStock** [comment]
close this?

**Comment by Beramos** [comment]
Nope, dat is de finale proofread checklist. Nog een laatste keer goed lezen
en de questions collapsen

Op vr 29 jan. 2021 15:40 schreef Michiel Stock <notifications@github.com>:
