### ISSUE TITLE
Weird convolution error project 1

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#52]
K_sharpen leads to values outside the interval [0, 1] so clamping is needed in the convolution.

**Comment by MichielStock** [comment]
This was an inaccuracy error. Fixed by automatically converting images to `Float32` in image convolution.

I also found a bug in the elementary CA, but it should be fixed now.

**Comment by Beramos** [comment]
Cool, thx. I only checked a few rules of the CA for correctness so it was
likely there was still a bug.

Op za 23 jan. 2021 16:00 schreef Michiel Stock <notifications@github.com>:
