### ISSUE TITLE
Looking the terminal

### ISSUE THREAD

**Issue by MichielStock** [Beramos/DS-Julia2925#56]
At several points, we ask the student to check the terminal for some result that was printed. As demonstrated in #54, PlutoUI has the option to show terminal results in the notebook. Someone should go through the notebooks implement this by default (perhaps when everything is more or less in a final phase).

**Comment by Beramos** [comment]
we might want to use #59 :wink:

**Comment by DaanVanHauwermeiren** [comment]
Already checked these files:
- [X] `01-basics.jl`
- [X] `02-collections.jl`
