### ISSUE TITLE
Designing "autograder"

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#6]

**Comment by Beramos** [comment]
The code is on the [grading branch](https://github.com/Beramos/DS-Julia2925/tree/grading)

**To do:**
- [ ] Put in module -> Bram
- [ ] Update example notebook -> Bram

Any ideas where we can let the students upload the finished notebooks? @MichielStock

**Comment by MichielStock** [comment]
We might also give a small homework notebook that they have to hand in lieu of everything? We only have to provide some evaluation.

**Comment by Beramos** [comment]
I would suggest that they hand in all the notebooks and projects and that
we just automatically count all the correct answers too conclude if they
pass.

Op ma 7 dec. 2020 21:58 schreef Michiel Stock <notifications@github.com>:

**Comment by Beramos** [comment]
Or is that not a good idea?

**Comment by MichielStock** [comment]
Seems good. I saw you made a tracker for the number of questions that were right, curious to try it out.

M

**Comment by Beramos** [comment]
Ok, I'll add an example asap then you can try it out :)

Op di 8 dec. 2020 10:09 schreef Michiel Stock <notifications@github.com>:

> Seems good. I saw you made a tracker for the number of questions that were
> right, curious to try it out.
>
> M
>
