### ISSUE TITLE
Bug in rejection sampling

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#64]
There still seems to be overlap after rejection sampling

![image](https://user-images.githubusercontent.com/11618908/106379752-739c1400-63ae-11eb-9497-d89d94b1d9a4.png)

Branch => project2

**Comment by MichielStock** [comment]
Triangles were tricky, but the final code should work (I haven't seen an example with intersecting triangles).

How about me moving the flatland code into a module in the `src`? I won't export it so there should be no conflicts. I can add some tests to check everything. You can load this for the checks of the exercises

**Comment by Beramos** [comment]
Great idea! Normally the example plotted at the bottom contains overlapping
triangles.

Op ma 1 feb. 2021 11:21 schreef Michiel Stock <notifications@github.com>:

**Comment by MichielStock** [comment]
Should be fixed by #70, leave it to you to close this.

**Comment by MichielStock** [comment]
I think I see the problem. The `in` function in the notebook is not valid for triangles, there is a different method for that. It was not the general case, sorry!

**Comment by MichielStock** [comment]
(it is correct for regular polygons)

**Comment by Beramos** [comment]
Fixed by #55
