### ISSUE TITLE
Add optional time filling question for Day 1 - basics

### ISSUE THREAD

**Issue by Beramos** [Beramos/DS-Julia2925#66]
Something to stall the fast workers, maybe something AOC-related

**Comment by Beramos** [comment]
I'm currently working on an exercises similar to https://adventofcode.com/2018/day/5

And @DaanVanHauwermeiren  is also working on a tricky exercise

**Comment by DaanVanHauwermeiren** [comment]
I made something based on https://adventofcode.com/2020/day/3 in PR #67
