### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by MichielStock** [Beramos/DS-Julia2925#74]
For day 1, I would like to show some aspects of improving the [performance](https://docs.julialang.org/en/v1/manual/performance-tips/). I wanted to test this on 2dconvolution but the compiler seems to be too smart. Anyone else has idea/examples of code that can be sped up/good practices on a toy example?

**Comment by Beramos** [comment]
Hmmm. I'm not that great yet at performance improvement, maybe it is better to just use an example from the web?

**Comment by Beramos** [comment]
@MichielStock is this still relevant?

**Comment by MichielStock** [comment]
Can be closed
