### ISSUE TITLE
[basics] pluto does not support readline

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [Beramos/DS-Julia2925#80]
file 01-basics.jl Question 6 part 2 fermat
pluto does not support readline
https://github.com/fonsp/Pluto.jl/discussions/765

**Comment by Beramos** [comment]
@DaanVanHauwermeiren not exactly sure what this is about. It this still relevant?

**Comment by wardvanbelle** [comment]
I changed the second question so readline() is no longer necessary
