### ISSUE TITLE
[collections] Riemann: automated checking for float should use approx.

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [Beramos/DS-Julia2925#81]
we should use `≈` instead of `==`
e.g. in Riemansum in 02-collections

**Comment by Beramos** [comment]
Even approx is still too strict, other implementations that use list comprehensions apparently are outside the tolerance of approx. Better to define a 0.1% margin of error

**Comment by wardvanbelle** [comment]
fixed it
