### ISSUE TITLE
[Basics] Question 8 - Error in Hint

### ISSUE THREAD

**Issue by lcdvissc** [Beramos/DS-Julia2925#88]
**Question 8: Molecular mass spectroscopy**
`replace(string1, "-CH2-CH2-" => "-CO-")` replaces all occurences of `"-CH2-CH2-"`; `replace(string1, "-CH2-CH2-" => "-CO-"; count = 1)` replaces only the first

**Comment by Beramos** [comment]
Oopsie! Thx. The rest of that question was fine?

Op za 6 feb. 2021 23:15 schreef Lander De Visscher <notifications@github.com

**Comment by wardvanbelle** [comment]
fixed it
